### ISSUE TITLE
Add ASF headers to Python files 

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk-package-kafka#148]
In preparation for bringing the code to Apache Software Foundation (ASF) it must be brought into compliance meaning all source code has legal ASF license headers.  This includes Python files and the new scanCode.py that will be dropped into openwhisk/tools/build will enable this check by default.   

A preliminary scan indicated this repo had the following Python files without headers:
scanCode.py .
Reading configuration file [/Users/Matt/python/scancode/scanCode.cfg]...
Scanning files starting at [.]...
Scan detected 13 error(s) in 9 file(s):
  [./openwhisk-package-kafka/action/kafkaProduce.py]:
       1: file does not include required license header.
  [./openwhisk-package-kafka/action/messageHubProduce.py]:
       1: file does not include required license header.
  [./openwhisk-package-kafka/provider/app.py]:
       1: file does not include required license header.
  [./openwhisk-package-kafka/provider/consumer.py]:
       1: file does not include required license header.
  [./openwhisk-package-kafka/provider/consumercollection.py]:
       1: file does not include required license header.
  [./openwhisk-package-kafka/provider/database.py]:
       1: file does not include required license header.
  [./openwhisk-package-kafka/provider/health.py]:
       1: file does not include required license header.
  [./openwhisk-package-kafka/provider/thedoctor.py]:
       1: file does not include required license header.

**Comment by dgrove-oss** [comment]
Already fixed
