### ISSUE TITLE
A list of source files missing Apache license headers

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/openwhisk-package-kafka#248]
Following [Apache license header guideline](http://www.apache.org/legal/src-headers.html), **all human-readable Apache-developed files that are included within a distribution must include the header text with few exceptions**. You can find few exceptions here: [which files do not require a license header](http://www.apache.org/legal/src-headers.html#faq-exceptions).

I used Apache Rat to check this repository after excluding a few files, and I got this report. We need to add Apache licensing header to below files.
```
Unapproved licenses:

  ./devGuide.md
  ./installCatalog.sh
  ./installKafka.sh
  ./action/kafkaFeed.js
  ./action/kafkaFeedWeb.js
  ./action/messageHubFeed.js
  ./action/messageHubFeedWeb.js
  ./action/lib/Database.js
  ./action/lib/common.js
  ./gradle/docker.gradle
  ./gradle/wrapper/gradle-wrapper.properties
  ./tests/build.gradle
  ./tools/travis/build.sh
  ./tools/travis/deploy.sh
  ./tools/travis/setup.sh
  ./tools/verifyDBMigration/index.js
```
The excluded files are:
```
# files copied from third parties or created by tools
gradlew
gradlew.bat

# JSON data file doesn't support annotation
.*json

# others
.gitignore
.rat-excludes
.gradle.properties
gradle-wrapper.properties
```

**Comment by dgrove-oss** [comment]
Already fixed.
