### ISSUE TITLE
Confusing deprecation comment in doc

### ISSUE THREAD

**Issue by pdykes** [apache/openwhisk-package-kafka#281]
This applies to the consumer as well, but I'm more focused on producer use case:

---- current doc ----
Producing messages to Message Hub

The /messaging/messageHubProduce Action is deprecated and will be removed at a future date. To maintain optimal performance, migrate your usage of the /messaging/messageHubProduce Action to use a persistent connection when data is produced to Message Hub.
---- current doc ----
Does this case support a maintain optimal performance use case, or is there something that offers this you are referring to? I need an efficient https/cloud function entry point, and then after some quick checks push into a Message Hub Kafka Instance (that is not configured in this cloud instance, so adding kafka credentials is very needed).  Does this doc imply that this solution provides a method, but not very efficient? And then is it stating to look elsewhere, but does not provide a solution or?  In any event, not sure if this is just trying to subtle, and saying, other than for demo use don't use it, or, this will work for heavy producer type scenarios wrt Cloud Functions and Message Hub...

**Comment by pheuberger** [comment]
I'm interested in this as well. Does OpenWhisk provice any functionality to make the recommended request over a persistent connection, or is this something we'd have to roll ourselves? If so, is there any documentation how to do so?

**Comment by pheuberger** [comment]
I'm bumping this issue, because in the Tokyo region `messageHubProduce` has already been removed and I expect this to happen in other regions soon as well. @jthomas Do you perhaps know how to best deal with this?

**Comment by rabbah** [comment]
> Does OpenWhisk provide any functionality to make the recommended request over a persistent connection

Do you mean persist a connection between an event source and the action container? You'd have to do this on your own and it would be for up to the action container's maximum allowed lifetime.

**Comment by srl295** [comment]
Ref: #265 @abaruni ?

**Comment by srl295** [comment]
Deprecation was in https://github.com/apache/openwhisk-package-kafka/pull/265
