### ISSUE TITLE
Update actions from nodejs:6 to nodejs:10

### ISSUE THREAD

**Issue by dgrove-oss** [apache/openwhisk-package-kafka#367]
The installCatalog.sh and installKafka.sh scripts select `nodejs:6` as the runtime kind.
NodeJS 6 is long past EOL; we need to update to select `nodejs:10` instead.

The actual change is trivial, but travisci is not setup to actually do comprehensive testing of this repository, so verifying that the actions all still work with the sparser dependencies of the nodejs:10 kind is where the work is.  Ideally, really travis testing would be configured as a side-effect of doing this work.

**Comment by Shariar076** [comment]
It doesn't work !! It just results in `error: Invalid argument(s). creating an action from a .zip artifact requires specifying the action kind explicitly`. Please update the code to newer runtime version. It is very unfortunate that one of the vital packages is not being updated with the main s/w.

**Comment by Shariar076** [comment]
It doesn't work!! Removing the parameter `--kind` just results in `error: Invalid argument(s). creating an action from a .zip artifact requires specifying the action kind explicitly`. 

Please update the code to newer runtime version. It is very unfortunate that one of the vital packages is not being updated with the main s/w.

**Comment by rabbah** [comment]
You can't remove the kind - the change looks like this https://github.com/apache/openwhisk-package-kafka/pull/369. But there aren't tests as Dave indicated for us to know the actions work in newer runtimes with no dependencies.

**Comment by rabbah** [comment]
Closed by #369.

**Comment by rabbah** [comment]
We still need to improve travisci but that's a different issue.

**Comment by Shariar076** [comment]
got it thanks

**Comment by Shariar076** [comment]
> You can't remove the kind - the change looks like this #369. But there aren't tests as Dave indicated for us to know the actions work in newer runtimes with no dependencies.

got it thanks
